---
title: "Simulation visualization"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggh4x)
library(RColorBrewer)
theme_set(theme_bw() +
  theme(
    legend.position = "none",
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    strip.background = element_rect(fill = "white", colour = "black"),
    panel.spacing.x = unit(1, "line"),
    panel.border = element_rect(color = "gray", fill = NA),
    axis.line.y = element_line(size = 0.5, linetype = "solid", colour = "black"),
    axis.line.x = element_line(size = 0.5, linetype = "solid", colour = "black"),
    axis.text.x = element_text(face = "bold"),
    axis.text.y = ggtext::element_markdown(),
    strip.text.x = element_text(face = "bold", size = 12),
    strip.text.y = element_text(face = "bold", size = 12)
  )
)

```

# Linear model visualization

## Theorem 1 checking with linear regression

```{r, fig.width=5, fig.height=3}
# Load the CSV file
sim_result <- read.csv('../linear_result_theorem_1/theorem_1_11082024.csv') %>% 
  filter(method == 'CS_on_mean') %>% 
  mutate(Method = ifelse(grepl("CS", method), "Theorem 1", "Naive")
         )
sim_result_cor1 <- read.csv('../linear_result_corrolary1/corollary_1_13082024.csv') %>% 
  filter(use_true_contour == "True", 
         method == 'CS_on_mean'
         ) %>% 
  mutate(Method = ifelse(grepl("CS", method), "Corollary 1", "Naive"),
         L = NA)
sim_result = rbind(sim_result, sim_result_cor1)


# Select specific columns
sim_result <- sim_result %>%
  select(L, N, p, Method, Lower_bound, contain, Upper_bound, points_in_e1, inner_points_num, outer_points_num)

# Optionally filter the data
sim_result_sub <- sim_result 

# Drop 'Lower_bound' column and rename others
t <- sim_result_sub %>%
  select(-Lower_bound) %>%
  rename(TLB = L,
         Coverage = contain,
         EUB = Upper_bound,
         `Points in IB` = points_in_e1,
         `Inner Set` = inner_points_num,
         `Outer set` = outer_points_num) %>%
  mutate(Coverage = ifelse(Coverage=="True",1,0)) %>% 
  group_by(p, TLB, N, Method) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  mutate(across(where(is.numeric), round, 4)) %>% 
  mutate(`Outcome Type` = ifelse(grepl("mean", Method), "Expected outcome", "Realized outcome"),
         Method = factor(Method, levels = c("Theorem 1", "Corollary 1"))
         ) 

ggplot(t, aes(x = factor(N), y = Coverage)) +
  geom_errorbar(aes(ymin = Coverage, ymax = EUB), position = position_dodge(0.7), width = 0.25) +
  geom_bar(stat = "identity", color="black", fill = "purple",fposition = position_dodge(), width = 0.7) +
  geom_hline(aes(yintercept = TLB), data = t,  linetype = "dashed") +
  scale_fill_brewer(palette = "Set1") +
  facet_grid(. ~ Method) +
  labs(x = "Training Sample Size (n)", y = "Coverage Rate", fill = "Method") +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90)
        ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     limits = c(0,1),
                     breaks = c(seq(0, 1, by = 0.3))
                     )

ggsave("./figures/thm_coro_sim_result.png", dpi = 300)
# t %>% ungroup() %>% 
#   select(TLB, Method, `Training Sample Size` = N, Coverage) %>% 
#   xtable::xtable()
```

## Linear regression

```{r, fig.width=8, fig.height=8}
# Load the CSV file
#sim_result <- read.csv('../linear_result/linear_regression_20072024.csv')
# result with the correct naive algorithm
sim_result <- read.csv('../linear_result/linear_regression_30122024.csv')

# Print unique values
print(unique(sim_result$data_kwargs))
print(unique(sim_result$model_kwargs_l))

# Select specific columns
sim_result <- sim_result %>%
  select(L, N, p, method, Lower_bound, contain,contain_CS_scb, Upper_bound, points_in_e1, inner_points_num, outer_points_num) %>% 
  pivot_longer(cols = c("contain_CS_scb", "contain"), names_to = "temp_method",
               values_to = "contain") %>%
  filter(contain!="") %>% 
  mutate(method = 
           case_when(
             grepl("mean", method) & temp_method =="contain_CS_scb"~ "naive_SCI_mean",
             grepl("y", method) & temp_method =="contain_CS_scb"~ "naive_SCI_y",
             method == "naive_on_y" ~ "naive_CI_y",
             method == "naive_on_mean" ~ "naive_CI_mean",
             TRUE~method
           ),
         Upper_bound = ifelse(grepl("CI", method), NA, Upper_bound)
  )

# Optionally filter the data
sim_result_sub <- sim_result # %>% filter(p == 6) # %>% filter(N != 800) # %>% filter(method == 'CS_on_mean')

# Drop 'Lower_bound' column and rename others
t <- sim_result_sub %>%
  select(-Lower_bound) %>%
  rename(TLB = L,
         Coverage = contain,
         EUB = Upper_bound,
         `Points in IB` = points_in_e1,
         `Inner Set` = inner_points_num,
         `Outer set` = outer_points_num) %>%
  mutate(Coverage = ifelse(Coverage=="True",1,0)) %>% 
  group_by(p, TLB, N, method) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  mutate(across(where(is.numeric), round, 2)) %>% 
  mutate(`Outcome Type` = ifelse(grepl("mean", method), "Expected outcome", "Realized outcome"),
         Method = case_when(grepl("CS", method)~"CS", 
                            grepl("SCI", method)~"SCI",
                            grepl("_CI_", method)~"CI",
                            ),
         Count = `Points in IB`
         )


ggplot(t, aes(x = factor(N), y = Coverage, fill = Method)) +
  geom_bar(stat = "identity", color="black", position = position_dodge(), width = 0.7) +
  geom_line(aes(y = Count/70, group = Method), color = "blue")+
  geom_hline(aes(yintercept = TLB), data = t,  linetype = "dashed") +
  geom_errorbar(aes(ymin = Coverage, ymax = EUB), position = position_dodge(0.7), width = 0.25) +
  scale_fill_brewer(palette = "Set1") +
  facet_nested(`Outcome Type`+TLB ~ p, labeller = labeller(p = label_both, TLB = label_both)) +
  labs(x = "Training Sample Size (n)", y = "Coverage Rate", fill = "Method") +
  theme(legend.position = "bottom",
        axis.title.y.right = element_text(color = "blue")
        ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     name = "Coverage Rate",
                     sec.axis = sec_axis(~.*70, 
                                         name = "# of Points in Inflated Boundary"),
                     breaks = c(seq(0, 1, by = 0.3))
                     )

ggsave("./figures/linear_sim_result.png", dpi = 300)
```

## Logistic regression

```{r, fig.width=8, fig.height=6}
# Load the CSV file
#sim_result <- read.csv('../linear_result/logistic_regression_20072024.csv')
#with SCI result
sim_result <- read.csv('../linear_result/logistic_regression_30122024.csv')

# Print unique values
print(unique(sim_result$data_kwargs))
print(unique(sim_result$model_kwargs_l))

# Select specific columns
sim_result <- sim_result %>%
  select(L, N, p, method, Lower_bound, contain,contain_CS_scb, Upper_bound, points_in_e1, inner_points_num, outer_points_num) %>% 
  pivot_longer(cols = c("contain_CS_scb", "contain"), names_to = "temp_method",
               values_to = "contain") %>%
  filter(contain!="") %>% 
  mutate(method = 
           case_when(
             grepl("mean", method) & temp_method =="contain_CS_scb"~ "naive_SCI_mean",
             grepl("y", method) & temp_method =="contain_CS_scb"~ "naive_SCI_y",
             method == "naive_on_y" ~ "naive_CI_y",
             method == "naive_on_mean" ~ "naive_CI_mean",
             TRUE~method
           ),
         Upper_bound = ifelse(grepl("CI", method), NA, Upper_bound)
  )

# Optionally filter the data
sim_result_sub <- sim_result # %>% filter(p == 6) # %>% filter(N != 800) # %>% filter(method == 'CS_on_mean')

# Drop 'Lower_bound' column and rename others
t <- sim_result_sub %>%
  select(-Lower_bound) %>%
  rename(TLB = L,
         Coverage = contain,
         EUB = Upper_bound,
         `Points in IB` = points_in_e1,
         `Inner Set` = inner_points_num,
         `Outer set` = outer_points_num) %>%
  mutate(Coverage = ifelse(Coverage=="True",1,0)) %>% 
  group_by(p, TLB, N, method) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  mutate(across(where(is.numeric), round, 2)) %>% 
  mutate(`Outcome Type` = ifelse(grepl("mean", method), "Expected outcome", "Realized outcome"),
         Method = case_when(grepl("CS", method)~"CS", 
                            grepl("SCI", method)~"SCI",
                            grepl("_CI_", method)~"CI",
                            ),
         Count = `Points in IB`
         )


ggplot(t, aes(x = factor(N), y = Coverage, fill = Method)) +
  geom_bar(stat = "identity", color="black", position = position_dodge(), width = 0.7) +
  geom_line(aes(y = Count/70, group = Method), color = "blue")+
  geom_hline(aes(yintercept = TLB), data = t,  linetype = "dashed") +
  geom_errorbar(aes(ymin = Coverage, ymax = EUB), position = position_dodge(0.7), width = 0.25) +
  scale_fill_brewer(palette = "Set1") +
  facet_nested(`Outcome Type`+TLB ~ p, labeller = labeller(p = label_both, TLB = label_both)) +
  labs(x = "Training Sample Size (n)", y = "Coverage Rate", fill = "Method") +
  theme(legend.position = "bottom",
        axis.title.y.right = element_text(color = "blue")
        ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     name = "Coverage Rate",
                     sec.axis = sec_axis(~.*70, 
                                         name = "# of Points in Inflated Boundary"),
                     breaks = c(seq(0, 1, by = 0.3))
                     )

ggsave("./figures/logistic_sim_result.png", dpi = 300)
```

# Non-linear data visualization

```{r fig.width=8, fig.height=8}
# Load the CSV file
sim_result_nerual <- read.csv('../nonlinear_result/neural_net_31122024_N=100.csv') %>% 
  rbind(read.csv('../nonlinear_result/neural_net_31122024_N=200.csv')) %>% 
  rbind(read.csv('../nonlinear_result/neural_net_31122024_N=400.csv')) %>% 
  rbind(read.csv('../nonlinear_result/neural_net_31122024_N=800.csv')) %>% 
  mutate(Model = "Neural Network")
# sim_result_xgboost <- read.csv('../nonlinear_result/xgboost_25072024.csv') %>% 
#   mutate(Model = "XGBoost")
sim_result_xgboost <- read.csv('../nonlinear_result/xgboost_30122024.csv') %>%
  mutate(Model = "XGBoost")

# Select specific columns
sim_result <- rbind(sim_result_nerual, sim_result_xgboost) %>%
  select(L, N, p, method, Lower_bound, contain,contain_CS_scb, Upper_bound, points_in_e1, inner_points_num, outer_points_num, Model) %>% 
  pivot_longer(cols = c("contain_CS_scb", "contain"), names_to = "temp_method",
               values_to = "contain") %>%
  filter(contain!="") %>% 
  mutate(method = 
           case_when(
             grepl("mean", method) & temp_method =="contain_CS_scb"~ "naive_SCI_mean",
             grepl("y", method) & temp_method =="contain_CS_scb"~ "naive_SCI_y",
             method == "naive_on_y" ~ "naive_CI_y",
             method == "naive_on_mean" ~ "naive_CI_mean",
             TRUE~method
           ),
         Upper_bound = ifelse(grepl("CI", method), NA, Upper_bound)
  )

# Optionally filter the data
sim_result_sub <- sim_result # %>% filter(p == 6) # %>% filter(N != 800) # %>% filter(method == 'CS_on_mean')

# Drop 'Lower_bound' column and rename others
t <- sim_result_sub %>%
  select(-Lower_bound) %>%
  rename(TLB = L,
         Coverage = contain,
         EUB = Upper_bound,
         `Points in IB` = points_in_e1,
         `Inner Set` = inner_points_num,
         `Outer set` = outer_points_num) %>%
  mutate(Coverage = ifelse(Coverage=="True",1,0)) %>% 
  group_by(p, TLB, N, method, Model) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  mutate(across(where(is.numeric), round, 2)) %>% 
  mutate(`Outcome Type` = ifelse(grepl("mean", method), "Expected outcome", "Realized outcome"),
         Method = case_when(grepl("CS", method)~"CS", 
                            grepl("SCI", method)~"SCI",
                            grepl("_CI_", method)~"CI",
                            ),
         Count = `Points in IB`
         )


ggplot(t, aes(x = factor(N), y = Coverage, fill = Method)) +
  geom_bar(stat = "identity", color="black", position = position_dodge(), width = 0.7) +
  geom_line(aes(y = Count/70, group = Method), color = "blue")+
  geom_hline(aes(yintercept = TLB), data = t,  linetype = "dashed") +
  geom_errorbar(aes(ymin = Coverage, ymax = EUB), position = position_dodge(0.7), width = 0.25) +
  scale_fill_brewer(palette = "Set1") +
  facet_nested(`Outcome Type`+TLB ~ Model, labeller = labeller(p = label_both, TLB = label_both)) +
  labs(x = "Training Sample Size (n)", y = "Coverage Rate", fill = "Method") +
  theme(legend.position = "bottom",
        axis.title.y.right = element_text(color = "blue")
        ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     name = "Coverage Rate",
                     sec.axis = sec_axis(~.*70, 
                                         name = "# of Points in Inflated Boundary"),
                     breaks = c(seq(0, 1, by = 0.3))
                     )

ggsave("./figures/nonlinear_sim_result.png", dpi = 300)
```
